[16.0][ADD] mrp_product_price_quick_menus
grap/grap-odoo-business pull request #158
Opened 2024-07-09 15:35 UTC by quentinDupont

2024-07-11 16:02 UTC, legalsylvain requested changes
remarques sur le design. 
(proposition de créer un module dédié dans la même PR).

2024-07-11 16:02 UTC, legalsylvain commented on mrp_product_price_quick_menus/views/view_product_product.xml
> +                <filter string="Finished products" name="filter_is_finished" domain="[('variant_bom_ids', '!=', False), ('bom_line_ids', '=', False)]"/>
on pourrait rajouter un group "bom_user" pour éviter de voir ce filtre si on fait pas de transfo ?

2024-07-11 16:02 UTC, legalsylvain commented on mrp_product_price_quick_menus/models/product_product.py
> +            product.date_last_statement_price = fields.Date.today()
Un peu du nitpicking. 
- je pense que ce fichier devrait aller dans un module générique ``product_standard_price_change_date``

- sinon, je pense qu'il faut l'initaliser avec la date du jour, quand on créé un produit

- + surcharger le write. (si standard_price dans le write, mettre la date du jour).

(ça ça fait que si on achète les matières premières, et qu'on utilise le module de mise à jour des infos fournisseurs avec le calcul du nouveau standard_price, il sera bien écrit à ce moment là.)

2024-07-25 09:50 UTC, quentinDupont commented on mrp_product_price_quick_menus/views/view_product_product.xml
> +                <filter string="Finished products" name="filter_is_finished" domain="[('variant_bom_ids', '!=', False), ('bom_line_ids', '=', False)]"/>
good idea !

2024-07-25 09:52 UTC, quentinDupont commented on mrp_product_price_quick_menus/models/product_product.py
> +            product.date_last_statement_price = fields.Date.today()
yes merci, on en avait parlé en plus

2024-07-25 10:39 UTC, legalsylvain commented
hello ! je crois que je me suis pas fait comprendre ! 
le module dédié, je le pensais pas pour le coup du bom_user : Je parlais du groupe existant : ``mrp.group_mrp_user``.

2024-07-25 13:01 UTC, quentinDupont commented
> hello ! je crois que je me suis pas fait comprendre ! le module dédié, je le pensais pas pour le coup du bom_user : sur ce sujet, Je parlais du groupe existant : `mrp.group_mrp_user`. je le pensais pour [#158 (comment)](https://github.com/grap/grap-odoo-business/pull/158#discussion_r1674285565)

Ah mais oui ok

2024-07-26 08:37 UTC, quentinDupont commented on mrp_product_price_quick_menus/views/view_product_product.xml
> +                <filter string="Finished products" name="filter_is_finished" domain="[('variant_bom_ids', '!=', False), ('bom_line_ids', '=', False)]"/>
En fait ça hérite de `mrp_product_product_search_view` et `mrp.mrp_product_template_search_view` donc ça se voit dans l'application mrp donc que si on est dans le group mrp.group_mrp_user

2024-07-26 09:53 UTC, quentinDupont commented on mrp_product_price_quick_menus/models/product_product.py
> +            product.date_last_statement_price = fields.Date.today()
done !

2024-07-26 12:06 UTC, legalsylvain commented on mrp_product_price_quick_menus/views/view_product_product.xml
> +                <filter string="Finished products" name="filter_is_finished" domain="[('variant_bom_ids', '!=', False), ('bom_line_ids', '=', False)]"/>
pas sûr d'avoir compris ! mais on verra bien en prod' !

2024-11-15 10:02 UTC, legalsylvain commented
MeP du 14/11/2024

/ocabot merge nobump

2024-11-15 10:06 UTC, merged