Purchase state no to be invoiced
grap/grap-odoo-business pull request #76
Opened 2021-02-18 15:12 UTC by quentinDupont

2021-03-01 19:22 UTC, legalsylvain requested changes

2021-03-01 19:22 UTC, legalsylvain commented on recurring_consignment_purchase/models/stock_picking.py
> +        order = order_obj.browse(self._context.get('active_id'))
Yop, 
- je pense qu'il faut que tu testes que le ``active_model`` est bien un ``purchase.order``, car si le picking est validé or d'un contexte de purchase, ça risque de générer une erreur.
- j'ai tenté de testé, mais quand j'installe le module ``recurring_consignment_purchase``, j'ai une erreur. je pense qu'il manque une dépendance. Tu peux checker ?

2021-03-08 10:12 UTC, legalsylvain approved these changes

2021-03-16 21:31 UTC, legalsylvain requested changes
Yop. je viens de retester. ça fonctionne pas.
quand on est sur un picking, le active_model est un picking (ce qui est normal) et le active_id est celui du picking, pas du order.
Je pense qu'il faut que tu récupères le order_id d'une autre façon plus fiable.

je pense que le champ natif du module purchase_stock doit pouvoir jouer.

https://github.com/odoo/odoo/blob/12.0/addons/purchase_stock/models/stock.py#L11

2021-03-16 21:31 UTC, legalsylvain commented on recurring_consignment_purchase/models/stock_picking.py
> +            super(Picking, self).button_validate()
il faut que la fonction super soit toujours appelée.

2021-03-16 21:31 UTC, legalsylvain commented on recurring_consignment_purchase/models/stock_picking.py
> +                order.invoice_status = 'no'
a la fin de la fonction, il faut renvoyé le résultat de la fonction super.

2021-03-30 12:22 UTC, quentinDupont commented
> Yop. je viens de retester. ça fonctionne pas.
> quand on est sur un picking, le active_model est un picking (ce qui est normal) et le active_id est celui du picking, pas du order.
> Je pense qu'il faut que tu récupères le order_id d'une autre façon plus fiable.
> 
> je pense que le champ natif du module purchase_stock doit pouvoir jouer.
> 
> https://github.com/odoo/odoo/blob/12.0/addons/purchase_stock/models/stock.py#L11

Ok en effet je comprenais pas la logique que l'active_id soit pas celui de l'objet courant, mais ça devait être le cas car je partais du purchase_order pour ensuite cliquer sur picking

je vois à modifier ça

2021-03-30 17:35 UTC, legalsylvain commented on recurring_consignment_purchase/models/stock_picking.py
> +            res = super(Picking, self)
Il faut aussi appeler button_validate() dans le cas ou c'est pas un achat. Sinon, le picking de vente ne se validera jamais.

Sinon c'est cool !

2021-03-31 07:29 UTC, quentinDupont commented on recurring_consignment_purchase/models/stock_picking.py
> +            res = super(Picking, self)
jsuis mauvais jacques

2021-04-01 21:29 UTC, legalsylvain commented
reloud. Travis est rouge. je comprend pas trop pourquoi. je tente une petite bidouille sur ta branche. (ref : dernier commit)

2021-04-02 12:21 UTC, quentinDupont commented
> reloud. Travis est rouge. je comprend pas trop pourquoi. je tente une petite bidouille sur ta branche. (ref : dernier commit)

Bien joué ! pas compris mais bien joué

2021-04-02 12:29 UTC, legalsylvain commented
moi non plus, pas compris. c'est un peu 2 magic lines qui parfois résolves des soucis quand des tests cassent pour des raisons obscures.
en fait, si je comprend bien, les tests sont éxécutés à la fin de l'installation de tous les modules, et non pas lors de l'installation des modules. dans certains cas, ça change des trucs.

2021-04-13 07:58 UTC, legalsylvain commented
MeP du 12/04/2021

/ocabot merge patch

2021-04-13 08:19 UTC, merged